/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InRouteImport } from './routes/_in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InProjectsRouteImport } from './routes/_in/projects'
import { Route as InBlogsIndexRouteImport } from './routes/_in/blogs.index'
import { Route as InBlogsSlugRouteImport } from './routes/_in/blogs.$slug'

const InRoute = InRouteImport.update({
  id: '/_in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InProjectsRoute = InProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => InRoute,
} as any)
const InBlogsIndexRoute = InBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => InRoute,
} as any)
const InBlogsSlugRoute = InBlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => InRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof InProjectsRoute
  '/blogs/$slug': typeof InBlogsSlugRoute
  '/blogs': typeof InBlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof InProjectsRoute
  '/blogs/$slug': typeof InBlogsSlugRoute
  '/blogs': typeof InBlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_in': typeof InRouteWithChildren
  '/_in/projects': typeof InProjectsRoute
  '/_in/blogs/$slug': typeof InBlogsSlugRoute
  '/_in/blogs/': typeof InBlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/blogs/$slug' | '/blogs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/blogs/$slug' | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/_in'
    | '/_in/projects'
    | '/_in/blogs/$slug'
    | '/_in/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InRoute: typeof InRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_in': {
      id: '/_in'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof InRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_in/projects': {
      id: '/_in/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof InProjectsRouteImport
      parentRoute: typeof InRoute
    }
    '/_in/blogs/': {
      id: '/_in/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof InBlogsIndexRouteImport
      parentRoute: typeof InRoute
    }
    '/_in/blogs/$slug': {
      id: '/_in/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof InBlogsSlugRouteImport
      parentRoute: typeof InRoute
    }
  }
}

interface InRouteChildren {
  InProjectsRoute: typeof InProjectsRoute
  InBlogsSlugRoute: typeof InBlogsSlugRoute
  InBlogsIndexRoute: typeof InBlogsIndexRoute
}

const InRouteChildren: InRouteChildren = {
  InProjectsRoute: InProjectsRoute,
  InBlogsSlugRoute: InBlogsSlugRoute,
  InBlogsIndexRoute: InBlogsIndexRoute,
}

const InRouteWithChildren = InRoute._addFileChildren(InRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InRoute: InRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
